mode: "dev"
port: 9091

log:
  level: "debug"
  filename: "./log/info.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: 1.117.147.234
  port: 3306
  user: root
  password: 123456
  db: db1
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: 124.70.71.78
  port: 16379
  db: 0